'use client';
import { useState } from 'react';
import { api } from '@/lib/motor';
type Finding={archivo:string;linea:number;fin:number;titulo:string;riesgo:string;evidencia:string;severidad:string;categoria:string};
type Report={fecha:string;alcance:string;archivos:{ruta:string}[];hallazgos:Finding[];descartados:unknown[]};
const button='rounded-lg bg-acento px-4 py-2 text-sm font-medium text-acento-tinta disabled:opacity-40';
const allowed=(name:string)=>/\.(m?[jt]sx?|cjs|py|rb|go|rs|java|php|html?|css|scss|sql|json|ya?ml|toml|conf)$/i.test(name)&&!name.split('/').some(p=>p.startsWith('.')||/^(node_modules|vendor|dist|build|out|coverage|data)$/i.test(p))&&!/(lock|secret|credential|private.?key|\.env)/i.test(name);
export default function RevisionCodigo({disabled=false}:{disabled?:boolean}){
 const [files,setFiles]=useState<{file:File;ruta:string;checked:boolean}[]>([]);
 const [excluded,setExcluded]=useState(0);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [report,setReport]=useState<Report|null>(null);
 const chosen=files.filter(f=>f.checked);const bytes=chosen.reduce((n,f)=>n+f.file.size,0);
 function choose(list:FileList|null){const all=Array.from(list||[]);const included=all.map(file=>({file,ruta:file.webkitRelativePath||file.name,checked:true})).filter(f=>allowed(f.ruta)&&f.file.size<=60000);setFiles(included);setExcluded(all.length-included.length);setReport(null);setMessage('');}
 async function analyze(){setBusy(true);setReport(null);setMessage('Bob está leyendo el código. Puede tardar hasta tres minutos…');try{const archivos=await Promise.all(chosen.map(async f=>({ruta:f.ruta,contenido:await f.file.text()})));setReport(await api<Report>('/codigo',{archivos}));setMessage('Análisis terminado. No se aplicaron cambios.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function download(){if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='revision-codigo.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <details className="mt-6 rounded-2xl border border-linea bg-superficie p-5 shadow-panel"><summary className="cursor-pointer text-sm font-semibold">Revisar código de un proyecto con Bob</summary><p className="mt-3 text-sm leading-relaxed text-tinta-media">Cargá los archivos de Wayfinder o de otro proyecto. Bob analiza seguridad, rendimiento y calidad del código fuente y señala archivo y línea.</p>
 <div className="mt-4 flex flex-wrap gap-4 text-sm"><label className="flex flex-col gap-2">Carpeta del proyecto<input type="file" multiple {...{webkitdirectory:''}} disabled={busy||disabled} onChange={e=>choose(e.target.files)} className="max-w-full text-xs"/></label><label className="flex flex-col gap-2">Archivos individuales<input type="file" multiple disabled={busy||disabled} onChange={e=>choose(e.target.files)} className="max-w-full text-xs"/></label></div>
 <p className="mt-4 text-xs text-tinta-suave">{chosen.length} archivos · {(bytes/1000).toFixed(1)} KB / máximo 180 KB y 80 archivos. {excluded} excluidos por tipo, carpeta o tamaño (60 KB por archivo).</p>
 <div className="mt-3 max-h-48 overflow-auto">{files.map((f,i)=><label key={f.ruta} className="flex items-center gap-2 py-1 font-mono text-xs"><input type="checkbox" checked={f.checked} disabled={busy} onChange={e=>setFiles(prev=>prev.map((x,j)=>j===i?{...x,checked:e.target.checked}:x))}/><span className="break-all">{f.ruta}</span></label>)}</div>
 <p className="my-4 text-xs leading-relaxed text-tinta-suave">El código seleccionado se envía a IBM Bob; no se publica en la galería. Revisá que no contenga claves ni datos privados: el filtro automático no detecta todos los secretos.</p><button className={button} disabled={disabled||busy||!chosen.length||chosen.length>80||bytes>180000} onClick={()=>void analyze()}>{busy?'Analizando…':'Analizar código'}</button><p role="status" className="mt-3 text-sm text-tinta-media">{message}</p>
 {report&&<section className="mt-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">Diagnóstico del código</h2><button className="text-xs text-acento" onClick={download}>Descargar informe JSON</button></div><p className="mt-2 text-xs text-tinta-suave">{report.archivos.length} archivos · {report.hallazgos.length} hallazgos con cita comprobada · {report.descartados.length} descartados. {report.alcance}</p>{!report.hallazgos.length&&<p className="mt-3 text-sm">No hubo hallazgos con evidencia verificable. Esto no garantiza que no existan problemas.</p>}{report.hallazgos.map((h,i)=><article key={i} className="mt-4 rounded-xl border border-linea p-4"><p className="text-xs uppercase text-acento">{h.severidad} · {h.categoria} · Diagnóstico por validar</p><h3 className="mt-2 font-medium">{h.titulo}</h3><p className="mt-2 break-all font-mono text-xs text-tinta-suave">{h.archivo}:{h.linea}–{h.fin}</p><p className="mt-2 text-sm leading-relaxed text-tinta-media">{h.riesgo}</p><pre className="mt-3 overflow-auto rounded bg-fondo p-3 text-xs">{h.evidencia}</pre></article>)}</section>}
 </details>;
}
